# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 칼퇴박사
email: seungil.you@gmail.com 
description: > # this means to ignore newlines until "baseurl:"
  Seungil You's personal blog.
  유승일의 개인 블로그입니다.
baseurl: "/blog_jekyll" # the subpath of your site, e.g. /blog
url: "http://seungilyou.gihub.io" # the base hostname & protocol for your site
twitter_username: youclid 
github_username:  seungilyou 

# Build settings
markdown: kramdown
